=== JarneLosschaert/jabberpoint-dfc/jabberpoint.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT presentation (showtitle?, slide+)>
<!ELEMENT showtitle (#PCDATA)>
<!ELEMENT slide (title, subject?, item*, toc?)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT subject (#PCDATA)>
<!ELEMENT item (#PCDATA)>
<!ATTLIST item
    kind CDATA #REQUIRED
    level CDATA #IMPLIED>
<!ELEMENT toc (#PCDATA)>

=== JarneLosschaert/jabberpoint-dfc/demo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE presentation SYSTEM "jabberpoint.dtd">
<presentation>
  <showtitle>Demo Slide Show</showtitle>
  <slide kind="title">
    <title>Demo Slide Show</title>
    <subject>Introduction</subject>
    <presenter>Stefano Igbinosun &amp; Jarne Losschaert</presenter>
    <date>2026-04-04</date>
  </slide>
  <slide>
    <title>Welcome</title>
    <subject>Introduction</subject>
    <item kind="text" level="0">Welcome to JabberPoint</item>
  </slide>
  <slide>
    <title>Goals</title>
    <subject>Introduction</subject>
    <item kind="text" level="1">What we will build</item>
  </slide>
  <slide>
    <toc/>
  </slide>
  <slide>
    <title>Architecture</title>
    <subject>Architecture</subject>
    <item kind="list">Onion architecture in layers
Layered dependencies
Separation of concerns</item>
  </slide>
  <slide>
    <title>Positioned Note</title>
    <subject>Architecture</subject>
    <item kind="position" x="40" y="120">Fixed position note</item>
  </slide>
  <slide>
    <title>Wrap-up</title>
    <item kind="text" level="1">Questions</item>
  </slide>
</presentation>
